### ISSUE TITLE
Wrong choper position

### ISSUE THREAD

**Issue by shazz** [salem-ok/PySprint#60]
After an accident the choper should pass exactly on top of the car, it seems to be slightly off.

**Comment by salem-ok** [comment]
@shazz could you add a screenshot please to explain the issue? Not sure exactly what you have in mind...

**Comment by shazz** [comment]
It's hard to take a screenshot but anyway, when the blue car crashed against the yellow/black order (see screenshot position), the choper was passing on the left of the car, where I put a red X instead of on top of the car.

![image](https://user-images.githubusercontent.com/604708/144751859-1dc8557d-f677-4437-9148-d9dbec61f012.png)

**Comment by salem-ok** [comment]
Thanks, I'll try to reproduce and pay attention!
