### ISSUE TITLE
Drone becomes dumb

### ISSUE THREAD

**Issue by shazz** [salem-ok/PySprint#77]
Sometimes a drone decide to keep going in a wall and never stops like the yellow drone on this screenshot:

![image](https://user-images.githubusercontent.com/604708/145693703-aaa5421c-4c8b-4456-ab52-ebe7adb1d968.png)

**Comment by salem-ok** [comment]
Yes... I am not super happy withe AI see #79 . I can probably tweak that local issue by updating the track json in the meantime...
